name: bmi_calculator
description: Rebuild of the BMI Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0" #There are newer versions but many potentially fatal changes must be made to accomodate them

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0   # ^8.4.0 - #the ^ enables us to use any version of the package thats 8.n

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
